image: gitpod/workspace-full

tasks:
  - init: |
      composer create-project laravel/laravel app
    command: |
      cd app
      php artisan serve --host=0.0.0.0 --port=8000

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - onecentlin.laravel-blade
    - bmewburn.vscode-intelephense-client
    - amiralizadeh9480.laravel-extra-intellisense
